-- Generated By protoc-gen-lua Do not Edit

local ModID_pbTable = {}


local protobuf = require "protobuf"
module('ModID_pb')


ModID_pbTable.MODID = protobuf.EnumDescriptor();
ModID_pbTable.MODID_LOGIN_MOD_ENUM = protobuf.EnumValueDescriptor();
ModID_pbTable.MODID_ROLE_MOD_ENUM = protobuf.EnumValueDescriptor();
ModID_pbTable.MODID_MAP_MOD_ENUM = protobuf.EnumValueDescriptor();
ModID_pbTable.MODID_TASK_MOD_ENUM = protobuf.EnumValueDescriptor();
ModID_pbTable.MODID_FRIEND_MOD_ENUM = protobuf.EnumValueDescriptor();
ModID_pbTable.MODID_SORTLIST_MOD_ENUM = protobuf.EnumValueDescriptor();
ModID_pbTable.MODID_GUILD_MOD_ENUM = protobuf.EnumValueDescriptor();
ModID_pbTable.MODID_MISC_MOD_ENUM = protobuf.EnumValueDescriptor();
ModID_pbTable.MODID_TEAM_MOD_ENUM = protobuf.EnumValueDescriptor();

ModID_pbTable.MODID_LOGIN_MOD_ENUM.name = "LOGIN_MOD"
ModID_pbTable.MODID_LOGIN_MOD_ENUM.index = 0
ModID_pbTable.MODID_LOGIN_MOD_ENUM.number = 1
ModID_pbTable.MODID_ROLE_MOD_ENUM.name = "ROLE_MOD"
ModID_pbTable.MODID_ROLE_MOD_ENUM.index = 1
ModID_pbTable.MODID_ROLE_MOD_ENUM.number = 2
ModID_pbTable.MODID_MAP_MOD_ENUM.name = "MAP_MOD"
ModID_pbTable.MODID_MAP_MOD_ENUM.index = 2
ModID_pbTable.MODID_MAP_MOD_ENUM.number = 3
ModID_pbTable.MODID_TASK_MOD_ENUM.name = "TASK_MOD"
ModID_pbTable.MODID_TASK_MOD_ENUM.index = 3
ModID_pbTable.MODID_TASK_MOD_ENUM.number = 4
ModID_pbTable.MODID_FRIEND_MOD_ENUM.name = "FRIEND_MOD"
ModID_pbTable.MODID_FRIEND_MOD_ENUM.index = 4
ModID_pbTable.MODID_FRIEND_MOD_ENUM.number = 5
ModID_pbTable.MODID_SORTLIST_MOD_ENUM.name = "SORTLIST_MOD"
ModID_pbTable.MODID_SORTLIST_MOD_ENUM.index = 5
ModID_pbTable.MODID_SORTLIST_MOD_ENUM.number = 6
ModID_pbTable.MODID_GUILD_MOD_ENUM.name = "GUILD_MOD"
ModID_pbTable.MODID_GUILD_MOD_ENUM.index = 6
ModID_pbTable.MODID_GUILD_MOD_ENUM.number = 7
ModID_pbTable.MODID_MISC_MOD_ENUM.name = "MISC_MOD"
ModID_pbTable.MODID_MISC_MOD_ENUM.index = 7
ModID_pbTable.MODID_MISC_MOD_ENUM.number = 8
ModID_pbTable.MODID_TEAM_MOD_ENUM.name = "TEAM_MOD"
ModID_pbTable.MODID_TEAM_MOD_ENUM.index = 8
ModID_pbTable.MODID_TEAM_MOD_ENUM.number = 9
ModID_pbTable.MODID.name = "ModID"
ModID_pbTable.MODID.full_name = ".Proto.ModID"
ModID_pbTable.MODID.values = {ModID_pbTable.MODID_LOGIN_MOD_ENUM,ModID_pbTable.MODID_ROLE_MOD_ENUM,ModID_pbTable.MODID_MAP_MOD_ENUM,ModID_pbTable.MODID_TASK_MOD_ENUM,ModID_pbTable.MODID_FRIEND_MOD_ENUM,ModID_pbTable.MODID_SORTLIST_MOD_ENUM,ModID_pbTable.MODID_GUILD_MOD_ENUM,ModID_pbTable.MODID_MISC_MOD_ENUM,ModID_pbTable.MODID_TEAM_MOD_ENUM}

FRIEND_MOD = 5
GUILD_MOD = 7
LOGIN_MOD = 1
MAP_MOD = 3
MISC_MOD = 8
ROLE_MOD = 2
SORTLIST_MOD = 6
TASK_MOD = 4
TEAM_MOD = 9


function GetNetMsg(funID)
end