//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Friend.proto
// Note: requires additional types generated from: ModID.proto
namespace FriendProto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stSynFriendInfo")]
  public partial class stSynFriendInfo : global::ProtoBuf.IExtensible
  {
    public stSynFriendInfo() {}
    
    private uint _charID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charID
    {
      get { return _charID; }
      set { _charID = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _job = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"job", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint job
    {
      get { return _job; }
      set { _job = value; }
    }
    private uint _sex = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private bool _online = default(bool);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"online", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool online
    {
      get { return _online; }
      set { _online = value; }
    }
    private uint _battlePower = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"battlePower", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint battlePower
    {
      get { return _battlePower; }
      set { _battlePower = value; }
    }
    private string _lastLoginTime = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"lastLoginTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string lastLoginTime
    {
      get { return _lastLoginTime; }
      set { _lastLoginTime = value; }
    }
    private uint _photoID = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"photoID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint photoID
    {
      get { return _photoID; }
      set { _photoID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stSynAllFriend")]
  public partial class stSynAllFriend : global::ProtoBuf.IExtensible
  {
    public stSynAllFriend() {}
    
    private readonly global::System.Collections.Generic.List<FriendProto.stSynFriendInfo> _allFriend = new global::System.Collections.Generic.List<FriendProto.stSynFriendInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"allFriend", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<FriendProto.stSynFriendInfo> allFriend
    {
      get { return _allFriend; }
    }
  
    private uint _fetchLilianNum = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"fetchLilianNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint fetchLilianNum
    {
      get { return _fetchLilianNum; }
      set { _fetchLilianNum = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _hasGiveLilianCharID = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(3, Name=@"hasGiveLilianCharID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> hasGiveLilianCharID
    {
      get { return _hasGiveLilianCharID; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=5)]
      ModID = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=1)]
      FunID = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stReqAddOneFriend")]
  public partial class stReqAddOneFriend : global::ProtoBuf.IExtensible
  {
    public stReqAddOneFriend() {}
    
    private uint _charID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charID
    {
      get { return _charID; }
      set { _charID = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=5)]
      ModID = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=2)]
      FunID = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stNotifyAddOneFriend")]
  public partial class stNotifyAddOneFriend : global::ProtoBuf.IExtensible
  {
    public stNotifyAddOneFriend() {}
    
    private FriendProto.stSynFriendInfo _data = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public FriendProto.stSynFriendInfo data
    {
      get { return _data; }
      set { _data = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=5)]
      ModID = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=3)]
      FunID = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stAddFriendTip")]
  public partial class stAddFriendTip : global::ProtoBuf.IExtensible
  {
    public stAddFriendTip() {}
    
    private uint _charID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charID
    {
      get { return _charID; }
      set { _charID = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=5)]
      ModID = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=4)]
      FunID = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stDelFriend")]
  public partial class stDelFriend : global::ProtoBuf.IExtensible
  {
    public stDelFriend() {}
    
    private uint _charID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charID
    {
      get { return _charID; }
      set { _charID = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=5)]
      ModID = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=5)]
      FunID = 5
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stFindAndAddFriend")]
  public partial class stFindAndAddFriend : global::ProtoBuf.IExtensible
  {
    public stFindAndAddFriend() {}
    
    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=5)]
      ModID = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=6)]
      FunID = 6
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stFindAndAddFriendResult")]
  public partial class stFindAndAddFriendResult : global::ProtoBuf.IExtensible
  {
    public stFindAndAddFriendResult() {}
    
    private uint _result = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=5)]
      ModID = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=7)]
      FunID = 7
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stReqApplyAddFriendList")]
  public partial class stReqApplyAddFriendList : global::ProtoBuf.IExtensible
  {
    public stReqApplyAddFriendList() {}
    
    private uint _flag = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=5)]
      ModID = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=8)]
      FunID = 8
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stSynApplyerInfo")]
  public partial class stSynApplyerInfo : global::ProtoBuf.IExtensible
  {
    public stSynApplyerInfo() {}
    
    private uint _charID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charID
    {
      get { return _charID; }
      set { _charID = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _job = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"job", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint job
    {
      get { return _job; }
      set { _job = value; }
    }
    private uint _sex = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private uint _applyDiffTime = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"applyDiffTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint applyDiffTime
    {
      get { return _applyDiffTime; }
      set { _applyDiffTime = value; }
    }
    private uint _battlePower = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"battlePower", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint battlePower
    {
      get { return _battlePower; }
      set { _battlePower = value; }
    }
    private uint _photoID = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"photoID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint photoID
    {
      get { return _photoID; }
      set { _photoID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stRetApplyAddFriendList")]
  public partial class stRetApplyAddFriendList : global::ProtoBuf.IExtensible
  {
    public stRetApplyAddFriendList() {}
    
    private readonly global::System.Collections.Generic.List<FriendProto.stSynApplyerInfo> _applyerList = new global::System.Collections.Generic.List<FriendProto.stSynApplyerInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"applyerList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<FriendProto.stSynApplyerInfo> applyerList
    {
      get { return _applyerList; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=5)]
      ModID = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=8)]
      FunID = 8
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stNotifyFriend")]
  public partial class stNotifyFriend : global::ProtoBuf.IExtensible
  {
    public stNotifyFriend() {}
    
    private uint _charID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charID
    {
      get { return _charID; }
      set { _charID = value; }
    }
    private FriendProto.NotifyFriendType _type = FriendProto.NotifyFriendType.NOTIFY_ONLINE;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(FriendProto.NotifyFriendType.NOTIFY_ONLINE)]
    public FriendProto.NotifyFriendType type
    {
      get { return _type; }
      set { _type = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=5)]
      ModID = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=9)]
      FunID = 9
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stSynRecommondChar")]
  public partial class stSynRecommondChar : global::ProtoBuf.IExtensible
  {
    public stSynRecommondChar() {}
    
    private uint _charID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charID
    {
      get { return _charID; }
      set { _charID = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _job = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"job", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint job
    {
      get { return _job; }
      set { _job = value; }
    }
    private uint _sex = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private uint _battlePower = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"battlePower", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint battlePower
    {
      get { return _battlePower; }
      set { _battlePower = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _photoID = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"photoID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint photoID
    {
      get { return _photoID; }
      set { _photoID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stReqRecommondFriend")]
  public partial class stReqRecommondFriend : global::ProtoBuf.IExtensible
  {
    public stReqRecommondFriend() {}
    
    private uint _charID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charID
    {
      get { return _charID; }
      set { _charID = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=5)]
      ModID = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=10)]
      FunID = 10
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stRecommondFriendList")]
  public partial class stRecommondFriendList : global::ProtoBuf.IExtensible
  {
    public stRecommondFriendList() {}
    
    private readonly global::System.Collections.Generic.List<FriendProto.stSynRecommondChar> _charList = new global::System.Collections.Generic.List<FriendProto.stSynRecommondChar>();
    [global::ProtoBuf.ProtoMember(1, Name=@"charList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<FriendProto.stSynRecommondChar> charList
    {
      get { return _charList; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=5)]
      ModID = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=11)]
      FunID = 11
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stGiveLilian2Friend")]
  public partial class stGiveLilian2Friend : global::ProtoBuf.IExtensible
  {
    public stGiveLilian2Friend() {}
    
    private uint _charID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charID
    {
      get { return _charID; }
      set { _charID = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=5)]
      ModID = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=12)]
      FunID = 12
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stGiveLilianResult")]
  public partial class stGiveLilianResult : global::ProtoBuf.IExtensible
  {
    public stGiveLilianResult() {}
    
    private uint _charID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charID
    {
      get { return _charID; }
      set { _charID = value; }
    }
    private FriendProto.stGiveLilianResult.eResult _result = FriendProto.stGiveLilianResult.eResult.eSUCCESS;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(FriendProto.stGiveLilianResult.eResult.eSUCCESS)]
    public FriendProto.stGiveLilianResult.eResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"eResult")]
    public enum eResult
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"eSUCCESS", Value=1)]
      eSUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eFAIL", Value=2)]
      eFAIL = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=5)]
      ModID = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=13)]
      FunID = 13
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stReqReceiveLilian")]
  public partial class stReqReceiveLilian : global::ProtoBuf.IExtensible
  {
    public stReqReceiveLilian() {}
    
    private uint _charID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charID
    {
      get { return _charID; }
      set { _charID = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=5)]
      ModID = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=14)]
      FunID = 14
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stReceiveLilianList")]
  public partial class stReceiveLilianList : global::ProtoBuf.IExtensible
  {
    public stReceiveLilianList() {}
    
    private readonly global::System.Collections.Generic.List<uint> _charIDs = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"charIDs", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> charIDs
    {
      get { return _charIDs; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=5)]
      ModID = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=15)]
      FunID = 15
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stFetchLilian")]
  public partial class stFetchLilian : global::ProtoBuf.IExtensible
  {
    public stFetchLilian() {}
    
    private FriendProto.eFetchLilianType _type = FriendProto.eFetchLilianType.FETCH_ONE;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(FriendProto.eFetchLilianType.FETCH_ONE)]
    public FriendProto.eFetchLilianType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _charID = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"charID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charID
    {
      get { return _charID; }
      set { _charID = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=5)]
      ModID = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=16)]
      FunID = 16
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stFetchLilianResult")]
  public partial class stFetchLilianResult : global::ProtoBuf.IExtensible
  {
    public stFetchLilianResult() {}
    
    private uint _result = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _charID = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"charID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charID
    {
      get { return _charID; }
      set { _charID = value; }
    }
    private FriendProto.eFetchLilianType _type = FriendProto.eFetchLilianType.FETCH_ONE;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(FriendProto.eFetchLilianType.FETCH_ONE)]
    public FriendProto.eFetchLilianType type
    {
      get { return _type; }
      set { _type = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"eResult")]
    public enum eResult
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"eSUCCESS", Value=1)]
      eSUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eNUM_USE_OUT", Value=2)]
      eNUM_USE_OUT = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eNOT_GIVE_LILIAN", Value=3)]
      eNOT_GIVE_LILIAN = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=5)]
      ModID = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=16)]
      FunID = 16
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stReqAdd2ApplyList")]
  public partial class stReqAdd2ApplyList : global::ProtoBuf.IExtensible
  {
    public stReqAdd2ApplyList() {}
    
    private uint _otherID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"otherID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint otherID
    {
      get { return _otherID; }
      set { _otherID = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=5)]
      ModID = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=17)]
      FunID = 17
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stAdd2ApplyListResult")]
  public partial class stAdd2ApplyListResult : global::ProtoBuf.IExtensible
  {
    public stAdd2ApplyListResult() {}
    
    private FriendProto.stAdd2ApplyListResult.eResult _result = FriendProto.stAdd2ApplyListResult.eResult.eSUCCESS;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(FriendProto.stAdd2ApplyListResult.eResult.eSUCCESS)]
    public FriendProto.stAdd2ApplyListResult.eResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"eResult")]
    public enum eResult
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"eSUCCESS", Value=1)]
      eSUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eFAIL", Value=2)]
      eFAIL = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=5)]
      ModID = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=18)]
      FunID = 18
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stRefuseAddFriend")]
  public partial class stRefuseAddFriend : global::ProtoBuf.IExtensible
  {
    public stRefuseAddFriend() {}
    
    private uint _charID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charID
    {
      get { return _charID; }
      set { _charID = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=5)]
      ModID = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=19)]
      FunID = 19
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stInvitePKWithFriend")]
  public partial class stInvitePKWithFriend : global::ProtoBuf.IExtensible
  {
    public stInvitePKWithFriend() {}
    
    private uint _charID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charID
    {
      get { return _charID; }
      set { _charID = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=5)]
      ModID = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=20)]
      FunID = 20
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stAskAgreePKWithFriend")]
  public partial class stAskAgreePKWithFriend : global::ProtoBuf.IExtensible
  {
    public stAskAgreePKWithFriend() {}
    
    private uint _charID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charID
    {
      get { return _charID; }
      set { _charID = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=5)]
      ModID = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=21)]
      FunID = 21
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stReplyFriendPKInvite")]
  public partial class stReplyFriendPKInvite : global::ProtoBuf.IExtensible
  {
    public stReplyFriendPKInvite() {}
    
    private bool _agree = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"agree", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool agree
    {
      get { return _agree; }
      set { _agree = value; }
    }
    private uint _charID = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"charID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charID
    {
      get { return _charID; }
      set { _charID = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=5)]
      ModID = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=22)]
      FunID = 22
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stInvitePKResult")]
  public partial class stInvitePKResult : global::ProtoBuf.IExtensible
  {
    public stInvitePKResult() {}
    
    private FriendProto.stInvitePKResult.eResult _result = FriendProto.stInvitePKResult.eResult.eRefuse;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(FriendProto.stInvitePKResult.eResult.eRefuse)]
    public FriendProto.stInvitePKResult.eResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"eResult")]
    public enum eResult
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"eRefuse", Value=1)]
      eRefuse = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eAgree", Value=2)]
      eAgree = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eNotYourFriend", Value=3)]
      eNotYourFriend = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eNotOnline", Value=4)]
      eNotOnline = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eInviteSuccess", Value=5)]
      eInviteSuccess = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=5)]
      ModID = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=22)]
      FunID = 22
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stReplyFriendPKInviteResult")]
  public partial class stReplyFriendPKInviteResult : global::ProtoBuf.IExtensible
  {
    public stReplyFriendPKInviteResult() {}
    
    private FriendProto.stReplyFriendPKInviteResult.eResult _result = FriendProto.stReplyFriendPKInviteResult.eResult.eNot_Invited_Has_Enter;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(FriendProto.stReplyFriendPKInviteResult.eResult.eNot_Invited_Has_Enter)]
    public FriendProto.stReplyFriendPKInviteResult.eResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"eResult")]
    public enum eResult
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"eNot_Invited_Has_Enter", Value=1)]
      eNot_Invited_Has_Enter = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=5)]
      ModID = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=23)]
      FunID = 23
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stSomeOneApplyAddFriend")]
  public partial class stSomeOneApplyAddFriend : global::ProtoBuf.IExtensible
  {
    public stSomeOneApplyAddFriend() {}
    
    private FriendProto.stSynApplyerInfo _one = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"one", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public FriendProto.stSynApplyerInfo one
    {
      get { return _one; }
      set { _one = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=5)]
      ModID = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=24)]
      FunID = 24
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MarryObjInfo")]
  public partial class MarryObjInfo : global::ProtoBuf.IExtensible
  {
    public MarryObjInfo() {}
    
    private uint _charID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charID
    {
      get { return _charID; }
      set { _charID = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _job = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"job", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint job
    {
      get { return _job; }
      set { _job = value; }
    }
    private uint _sex = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private uint _battlePower = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"battlePower", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint battlePower
    {
      get { return _battlePower; }
      set { _battlePower = value; }
    }
    private uint _headID = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"headID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint headID
    {
      get { return _headID; }
      set { _headID = value; }
    }
    private uint _bodyID = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"bodyID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint bodyID
    {
      get { return _bodyID; }
      set { _bodyID = value; }
    }
    private uint _weaponID = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"weaponID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint weaponID
    {
      get { return _weaponID; }
      set { _weaponID = value; }
    }
    private uint _cloackID = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"cloackID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cloackID
    {
      get { return _cloackID; }
      set { _cloackID = value; }
    }
    private uint _wingID = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"wingID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint wingID
    {
      get { return _wingID; }
      set { _wingID = value; }
    }
    private uint _shoeID = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"shoeID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint shoeID
    {
      get { return _shoeID; }
      set { _shoeID = value; }
    }
    private uint _fashionHair = default(uint);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"fashionHair", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint fashionHair
    {
      get { return _fashionHair; }
      set { _fashionHair = value; }
    }
    private uint _fashionFace = default(uint);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"fashionFace", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint fashionFace
    {
      get { return _fashionFace; }
      set { _fashionFace = value; }
    }
    private uint _fashionBody = default(uint);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"fashionBody", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint fashionBody
    {
      get { return _fashionBody; }
      set { _fashionBody = value; }
    }
    private uint _fashionWeapon = default(uint);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"fashionWeapon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint fashionWeapon
    {
      get { return _fashionWeapon; }
      set { _fashionWeapon = value; }
    }
    private uint _fashionShoe = default(uint);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"fashionShoe", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint fashionShoe
    {
      get { return _fashionShoe; }
      set { _fashionShoe = value; }
    }
    private uint _fashionDecoration = default(uint);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"fashionDecoration", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint fashionDecoration
    {
      get { return _fashionDecoration; }
      set { _fashionDecoration = value; }
    }
    private uint _effectID = default(uint);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"effectID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint effectID
    {
      get { return _effectID; }
      set { _effectID = value; }
    }
    private uint _wingBreakLv = default(uint);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"wingBreakLv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint wingBreakLv
    {
      get { return _wingBreakLv; }
      set { _wingBreakLv = value; }
    }
    private uint _fashionWingID = default(uint);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"fashionWingID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint fashionWingID
    {
      get { return _fashionWingID; }
      set { _fashionWingID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stReqPropose")]
  public partial class stReqPropose : global::ProtoBuf.IExtensible
  {
    public stReqPropose() {}
    
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private FriendProto.MarryObjInfo _info = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public FriendProto.MarryObjInfo info
    {
      get { return _info; }
      set { _info = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=5)]
      ModID = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=25)]
      FunID = 25
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RejectMarry")]
  public partial class RejectMarry : global::ProtoBuf.IExtensible
  {
    public RejectMarry() {}
    
    private FriendProto.RejectMarry.Result _result = FriendProto.RejectMarry.Result.RESULT_SUCCESS;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(FriendProto.RejectMarry.Result.RESULT_SUCCESS)]
    public FriendProto.RejectMarry.Result result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _tick1 = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tick1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint tick1
    {
      get { return _tick1; }
      set { _tick1 = value; }
    }
    private uint _tick2 = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"tick2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint tick2
    {
      get { return _tick2; }
      set { _tick2 = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Result")]
    public enum Result
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"RESULT_SUCCESS", Value=1)]
      RESULT_SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RESULT_ERROR_FRIEND", Value=2)]
      RESULT_ERROR_FRIEND = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RESULT_ERROR_ONLINE", Value=3)]
      RESULT_ERROR_ONLINE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RESULT_ERROR_SEX", Value=4)]
      RESULT_ERROR_SEX = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RESULT_ERROR_MARRIED", Value=5)]
      RESULT_ERROR_MARRIED = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RESULT_ERROR_TICK1", Value=6)]
      RESULT_ERROR_TICK1 = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RESULT_ERROR_TICK2", Value=7)]
      RESULT_ERROR_TICK2 = 7
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=5)]
      ModID = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=26)]
      FunID = 26
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProposeResult")]
  public partial class ProposeResult : global::ProtoBuf.IExtensible
  {
    public ProposeResult() {}
    
    private FriendProto.ProposeResult.Result _result = FriendProto.ProposeResult.Result.RESULT_SUCCESS;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(FriendProto.ProposeResult.Result.RESULT_SUCCESS)]
    public FriendProto.ProposeResult.Result result
    {
      get { return _result; }
      set { _result = value; }
    }
    private FriendProto.MarryObjInfo _info = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public FriendProto.MarryObjInfo info
    {
      get { return _info; }
      set { _info = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Result")]
    public enum Result
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"RESULT_SUCCESS", Value=1)]
      RESULT_SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RESULT_REFUSE", Value=2)]
      RESULT_REFUSE = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=5)]
      ModID = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=27)]
      FunID = 27
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stReqAgreeMarry")]
  public partial class stReqAgreeMarry : global::ProtoBuf.IExtensible
  {
    public stReqAgreeMarry() {}
    
    private FriendProto.stReqAgreeMarry.Result _result = FriendProto.stReqAgreeMarry.Result.RESULT_AGREE;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(FriendProto.stReqAgreeMarry.Result.RESULT_AGREE)]
    public FriendProto.stReqAgreeMarry.Result result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Result")]
    public enum Result
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"RESULT_AGREE", Value=1)]
      RESULT_AGREE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RESULT_REFUSE", Value=2)]
      RESULT_REFUSE = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=5)]
      ModID = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=28)]
      FunID = 28
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stReqCancelMarry")]
  public partial class stReqCancelMarry : global::ProtoBuf.IExtensible
  {
    public stReqCancelMarry() {}
    
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=5)]
      ModID = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=29)]
      FunID = 29
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NotifyCancelMarry")]
  public partial class NotifyCancelMarry : global::ProtoBuf.IExtensible
  {
    public NotifyCancelMarry() {}
    
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=5)]
      ModID = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=30)]
      FunID = 30
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NotifyAgree")]
  public partial class NotifyAgree : global::ProtoBuf.IExtensible
  {
    public NotifyAgree() {}
    
    private FriendProto.NotifyAgree.Result _result = FriendProto.NotifyAgree.Result.RESULT_SUCCESS;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(FriendProto.NotifyAgree.Result.RESULT_SUCCESS)]
    public FriendProto.NotifyAgree.Result result
    {
      get { return _result; }
      set { _result = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Result")]
    public enum Result
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"RESULT_SUCCESS", Value=1)]
      RESULT_SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RESULT_ONLINE", Value=2)]
      RESULT_ONLINE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RESULT_CANCEL", Value=3)]
      RESULT_CANCEL = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RESULT_WEDDING", Value=4)]
      RESULT_WEDDING = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=5)]
      ModID = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=31)]
      FunID = 31
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"NotifyFriendType")]
    public enum NotifyFriendType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_ONLINE", Value=1)]
      NOTIFY_ONLINE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_OFFLINE", Value=2)]
      NOTIFY_OFFLINE = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eFetchLilianType")]
    public enum eFetchLilianType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FETCH_ONE", Value=1)]
      FETCH_ONE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FETCH_ALL", Value=2)]
      FETCH_ALL = 2
    }
  
}