//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Login.proto
// Note: requires additional types generated from: ModID.proto
namespace Login
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqLogin")]
  public partial class ReqLogin : global::ProtoBuf.IExtensible
  {
    public ReqLogin() {}
    
    private string _account = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private string _password = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=1)]
      ModID = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=1)]
      FunID = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RetLoginSucess")]
  public partial class RetLoginSucess : global::ProtoBuf.IExtensible
  {
    public RetLoginSucess() {}
    
    private string _token = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string token
    {
      get { return _token; }
      set { _token = value; }
    }
    private string _ip = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ip
    {
      get { return _ip; }
      set { _ip = value; }
    }
    private string _device = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"device", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string device
    {
      get { return _device; }
      set { _device = value; }
    }
    private uint _opID = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"opID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint opID
    {
      get { return _opID; }
      set { _opID = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=1)]
      ModID = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=2)]
      FunID = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginError")]
  public partial class LoginError : global::ProtoBuf.IExtensible
  {
    public LoginError() {}
    
    private uint _errorType = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"errorType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint errorType
    {
      get { return _errorType; }
      set { _errorType = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ErrorType")]
    public enum ErrorType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PASSWORD_WRONG", Value=1)]
      PASSWORD_WRONG = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HAS_LOGIN_IN", Value=2)]
      HAS_LOGIN_IN = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OTHER", Value=3)]
      OTHER = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_IN_OTHER_PLACE", Value=4)]
      LOGIN_IN_OTHER_PLACE = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_VERSION_TOO_LOW", Value=5)]
      LOGIN_VERSION_TOO_LOW = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoID")]
    public enum ProtoID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=1)]
      ModID = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=3)]
      FunID = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqLoginGate")]
  public partial class ReqLoginGate : global::ProtoBuf.IExtensible
  {
    public ReqLoginGate() {}
    
    private string _token = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string token
    {
      get { return _token; }
      set { _token = value; }
    }
    private string _deviceID = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"deviceID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string deviceID
    {
      get { return _deviceID; }
      set { _deviceID = value; }
    }
    private string _ip = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ip
    {
      get { return _ip; }
      set { _ip = value; }
    }
    private uint _opID = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"opID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint opID
    {
      get { return _opID; }
      set { _opID = value; }
    }
    private uint _clientVersion = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"clientVersion", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint clientVersion
    {
      get { return _clientVersion; }
      set { _clientVersion = value; }
    }
    private uint _serverID = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"serverID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint serverID
    {
      get { return _serverID; }
      set { _serverID = value; }
    }
    private string _extraData = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"extraData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string extraData
    {
      get { return _extraData; }
      set { _extraData = value; }
    }
    private uint _sdkId = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"sdkId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sdkId
    {
      get { return _sdkId; }
      set { _sdkId = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoID")]
    public enum ProtoID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=1)]
      ModID = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=4)]
      FunID = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stReqServerTime")]
  public partial class stReqServerTime : global::ProtoBuf.IExtensible
  {
    public stReqServerTime() {}
    
    private uint _flag = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoID")]
    public enum ProtoID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=1)]
      ModID = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=5)]
      FunID = 5
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stRetServerTime")]
  public partial class stRetServerTime : global::ProtoBuf.IExtensible
  {
    public stRetServerTime() {}
    
    private uint _svrTime = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"svrTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint svrTime
    {
      get { return _svrTime; }
      set { _svrTime = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoID")]
    public enum ProtoID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=1)]
      ModID = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=6)]
      FunID = 6
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stAutoLoginGate")]
  public partial class stAutoLoginGate : global::ProtoBuf.IExtensible
  {
    public stAutoLoginGate() {}
    
    private string _token = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string token
    {
      get { return _token; }
      set { _token = value; }
    }
    private string _deviceID = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"deviceID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string deviceID
    {
      get { return _deviceID; }
      set { _deviceID = value; }
    }
    private string _ip = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ip
    {
      get { return _ip; }
      set { _ip = value; }
    }
    private uint _opID = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"opID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint opID
    {
      get { return _opID; }
      set { _opID = value; }
    }
    private string _extraData = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"extraData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string extraData
    {
      get { return _extraData; }
      set { _extraData = value; }
    }
    private uint _sdkId = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"sdkId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sdkId
    {
      get { return _sdkId; }
      set { _sdkId = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoID")]
    public enum ProtoID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=1)]
      ModID = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=7)]
      FunID = 7
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stNotifyRelogin")]
  public partial class stNotifyRelogin : global::ProtoBuf.IExtensible
  {
    public stNotifyRelogin() {}
    
    [global::ProtoBuf.ProtoContract(Name=@"ProtoID")]
    public enum ProtoID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=1)]
      ModID = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=8)]
      FunID = 8
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stQueryPingValue")]
  public partial class stQueryPingValue : global::ProtoBuf.IExtensible
  {
    public stQueryPingValue() {}
    
    private uint _curTime = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"curTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint curTime
    {
      get { return _curTime; }
      set { _curTime = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoID")]
    public enum ProtoID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=1)]
      ModID = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=9)]
      FunID = 9
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stReqClientTime")]
  public partial class stReqClientTime : global::ProtoBuf.IExtensible
  {
    public stReqClientTime() {}
    
    private uint _curTime = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"curTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint curTime
    {
      get { return _curTime; }
      set { _curTime = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoID")]
    public enum ProtoID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=1)]
      ModID = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=10)]
      FunID = 10
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stSendClient2Svr")]
  public partial class stSendClient2Svr : global::ProtoBuf.IExtensible
  {
    public stSendClient2Svr() {}
    
    private uint _curTime = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"curTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint curTime
    {
      get { return _curTime; }
      set { _curTime = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoID")]
    public enum ProtoID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=1)]
      ModID = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=11)]
      FunID = 11
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stNotifyIsNewAccount")]
  public partial class stNotifyIsNewAccount : global::ProtoBuf.IExtensible
  {
    public stNotifyIsNewAccount() {}
    
    private bool _isNewAcc = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"isNewAcc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isNewAcc
    {
      get { return _isNewAcc; }
      set { _isNewAcc = value; }
    }
    private string _account = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoID")]
    public enum ProtoID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=1)]
      ModID = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=12)]
      FunID = 12
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"LOGIN_MOD")]
    public enum LOGIN_MOD
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqLogin_req", Value=1)]
      ReqLogin_req = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RetLoginSucess_rsp", Value=2)]
      RetLoginSucess_rsp = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LoginError_rsp", Value=3)]
      LoginError_rsp = 3
    }
  
}