//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ModID.proto
namespace Proto
{
    [global::ProtoBuf.ProtoContract(Name=@"ModID")]
    public enum ModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_MOD", Value=1)]
      LOGIN_MOD = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROLE_MOD", Value=2)]
      ROLE_MOD = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAP_MOD", Value=3)]
      MAP_MOD = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TASK_MOD", Value=4)]
      TASK_MOD = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FRIEND_MOD", Value=5)]
      FRIEND_MOD = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SORTLIST_MOD", Value=6)]
      SORTLIST_MOD = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GUILD_MOD", Value=7)]
      GUILD_MOD = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MISC_MOD", Value=8)]
      MISC_MOD = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TEAM_MOD", Value=9)]
      TEAM_MOD = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MISC2_MOD", Value=10)]
      MISC2_MOD = 10
    }
  
}