//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Task.proto
// Note: requires additional types generated from: ModID.proto
namespace TaskProto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stSynFinishTaskID")]
  public partial class stSynFinishTaskID : global::ProtoBuf.IExtensible
  {
    public stSynFinishTaskID() {}
    
    private readonly global::System.Collections.Generic.List<uint> _finishTaskIDList = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"finishTaskIDList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> finishTaskIDList
    {
      get { return _finishTaskIDList; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=4)]
      ModID = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=1)]
      FunID = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stNotifyTaskFinish")]
  public partial class stNotifyTaskFinish : global::ProtoBuf.IExtensible
  {
    public stNotifyTaskFinish() {}
    
    private uint _taskID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"taskID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint taskID
    {
      get { return _taskID; }
      set { _taskID = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=4)]
      ModID = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=2)]
      FunID = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stTaskCounter")]
  public partial class stTaskCounter : global::ProtoBuf.IExtensible
  {
    public stTaskCounter() {}
    
    private TaskProto.GAME_EVENT_TYPE _eventType = TaskProto.GAME_EVENT_TYPE.ET_FINISH_COPYMAP;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"eventType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(TaskProto.GAME_EVENT_TYPE.ET_FINISH_COPYMAP)]
    public TaskProto.GAME_EVENT_TYPE eventType
    {
      get { return _eventType; }
      set { _eventType = value; }
    }
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _value = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stSynTaskInfo")]
  public partial class stSynTaskInfo : global::ProtoBuf.IExtensible
  {
    public stSynTaskInfo() {}
    
    private uint _taskID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"taskID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint taskID
    {
      get { return _taskID; }
      set { _taskID = value; }
    }
    private uint _ts = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ts", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint ts
    {
      get { return _ts; }
      set { _ts = value; }
    }
    private readonly global::System.Collections.Generic.List<TaskProto.stTaskCounter> _counter = new global::System.Collections.Generic.List<TaskProto.stTaskCounter>();
    [global::ProtoBuf.ProtoMember(3, Name=@"counter", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<TaskProto.stTaskCounter> counter
    {
      get { return _counter; }
    }
  
    private uint _subTs = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"subTs", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint subTs
    {
      get { return _subTs; }
      set { _subTs = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stSynAllAcceptTask")]
  public partial class stSynAllAcceptTask : global::ProtoBuf.IExtensible
  {
    public stSynAllAcceptTask() {}
    
    private readonly global::System.Collections.Generic.List<TaskProto.stSynTaskInfo> _taskInfoList = new global::System.Collections.Generic.List<TaskProto.stSynTaskInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"taskInfoList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<TaskProto.stSynTaskInfo> taskInfoList
    {
      get { return _taskInfoList; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=4)]
      ModID = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=3)]
      FunID = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stReqAcceptTask")]
  public partial class stReqAcceptTask : global::ProtoBuf.IExtensible
  {
    public stReqAcceptTask() {}
    
    private uint _taskID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"taskID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint taskID
    {
      get { return _taskID; }
      set { _taskID = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=4)]
      ModID = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=4)]
      FunID = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stNotifyAddTask")]
  public partial class stNotifyAddTask : global::ProtoBuf.IExtensible
  {
    public stNotifyAddTask() {}
    
    private TaskProto.stSynTaskInfo _taskInfo = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"taskInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public TaskProto.stSynTaskInfo taskInfo
    {
      get { return _taskInfo; }
      set { _taskInfo = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=4)]
      ModID = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=5)]
      FunID = 5
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stAcceptTaskError")]
  public partial class stAcceptTaskError : global::ProtoBuf.IExtensible
  {
    public stAcceptTaskError() {}
    
    private TaskProto.stAcceptTaskError.eReason _reason = TaskProto.stAcceptTaskError.eReason.eCon_Not_Enough;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(TaskProto.stAcceptTaskError.eReason.eCon_Not_Enough)]
    public TaskProto.stAcceptTaskError.eReason reason
    {
      get { return _reason; }
      set { _reason = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"eReason")]
    public enum eReason
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"eCon_Not_Enough", Value=1)]
      eCon_Not_Enough = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=4)]
      ModID = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=6)]
      FunID = 6
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stRefreshTaskInfo")]
  public partial class stRefreshTaskInfo : global::ProtoBuf.IExtensible
  {
    public stRefreshTaskInfo() {}
    
    private TaskProto.stSynTaskInfo _taskInfo = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"taskInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public TaskProto.stSynTaskInfo taskInfo
    {
      get { return _taskInfo; }
      set { _taskInfo = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=4)]
      ModID = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=7)]
      FunID = 7
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stReqCommitTask")]
  public partial class stReqCommitTask : global::ProtoBuf.IExtensible
  {
    public stReqCommitTask() {}
    
    private uint _taskID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"taskID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint taskID
    {
      get { return _taskID; }
      set { _taskID = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=4)]
      ModID = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=8)]
      FunID = 8
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stCommitTaskResult")]
  public partial class stCommitTaskResult : global::ProtoBuf.IExtensible
  {
    public stCommitTaskResult() {}
    
    private TaskProto.stCommitTaskResult.eResult _result = TaskProto.stCommitTaskResult.eResult.eSUCCESS;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(TaskProto.stCommitTaskResult.eResult.eSUCCESS)]
    public TaskProto.stCommitTaskResult.eResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _taskID = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"taskID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint taskID
    {
      get { return _taskID; }
      set { _taskID = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"eResult")]
    public enum eResult
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"eSUCCESS", Value=1)]
      eSUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eCON_NOT_ENOUGH", Value=2)]
      eCON_NOT_ENOUGH = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=4)]
      ModID = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=9)]
      FunID = 9
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stChgTaskSubStatus")]
  public partial class stChgTaskSubStatus : global::ProtoBuf.IExtensible
  {
    public stChgTaskSubStatus() {}
    
    private uint _taskID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"taskID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint taskID
    {
      get { return _taskID; }
      set { _taskID = value; }
    }
    private uint _subTs = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"subTs", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint subTs
    {
      get { return _subTs; }
      set { _subTs = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=4)]
      ModID = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=10)]
      FunID = 10
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stSaveCurrentTask")]
  public partial class stSaveCurrentTask : global::ProtoBuf.IExtensible
  {
    public stSaveCurrentTask() {}
    
    private uint _curTaskID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"curTaskID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint curTaskID
    {
      get { return _curTaskID; }
      set { _curTaskID = value; }
    }
    private uint _curStage = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"curStage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint curStage
    {
      get { return _curStage; }
      set { _curStage = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=4)]
      ModID = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=11)]
      FunID = 11
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stNotifyCurrentTask")]
  public partial class stNotifyCurrentTask : global::ProtoBuf.IExtensible
  {
    public stNotifyCurrentTask() {}
    
    private uint _curTaskID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"curTaskID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint curTaskID
    {
      get { return _curTaskID; }
      set { _curTaskID = value; }
    }
    private uint _curState = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"curState", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint curState
    {
      get { return _curState; }
      set { _curState = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=4)]
      ModID = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=12)]
      FunID = 12
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stReqBatchAcceptTask")]
  public partial class stReqBatchAcceptTask : global::ProtoBuf.IExtensible
  {
    public stReqBatchAcceptTask() {}
    
    private readonly global::System.Collections.Generic.List<uint> _taskIDs = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"taskIDs", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> taskIDs
    {
      get { return _taskIDs; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=4)]
      ModID = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=13)]
      FunID = 13
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stRetBatchAccpetTask")]
  public partial class stRetBatchAccpetTask : global::ProtoBuf.IExtensible
  {
    public stRetBatchAccpetTask() {}
    
    private readonly global::System.Collections.Generic.List<TaskProto.stSynTaskInfo> _taskInfos = new global::System.Collections.Generic.List<TaskProto.stSynTaskInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"taskInfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<TaskProto.stSynTaskInfo> taskInfos
    {
      get { return _taskInfos; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=4)]
      ModID = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=14)]
      FunID = 14
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stSynDailyTaskScore")]
  public partial class stSynDailyTaskScore : global::ProtoBuf.IExtensible
  {
    public stSynDailyTaskScore() {}
    
    private uint _num = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint num
    {
      get { return _num; }
      set { _num = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=4)]
      ModID = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=15)]
      FunID = 15
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stDailyTaskScoreInfo")]
  public partial class stDailyTaskScoreInfo : global::ProtoBuf.IExtensible
  {
    public stDailyTaskScoreInfo() {}
    
    private uint _dailyTaskScore = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"dailyTaskScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint dailyTaskScore
    {
      get { return _dailyTaskScore; }
      set { _dailyTaskScore = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _rewardIDs = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"rewardIDs", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> rewardIDs
    {
      get { return _rewardIDs; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=4)]
      ModID = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=16)]
      FunID = 16
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stReqDailyTaskScoreReward")]
  public partial class stReqDailyTaskScoreReward : global::ProtoBuf.IExtensible
  {
    public stReqDailyTaskScoreReward() {}
    
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=4)]
      ModID = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=17)]
      FunID = 17
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stDailyTaskScoreRewardResult")]
  public partial class stDailyTaskScoreRewardResult : global::ProtoBuf.IExtensible
  {
    public stDailyTaskScoreRewardResult() {}
    
    private TaskProto.stDailyTaskScoreRewardResult.eResult _result = TaskProto.stDailyTaskScoreRewardResult.eResult.eSuccess;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(TaskProto.stDailyTaskScoreRewardResult.eResult.eSuccess)]
    public TaskProto.stDailyTaskScoreRewardResult.eResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"eResult")]
    public enum eResult
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"eSuccess", Value=1)]
      eSuccess = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eScore_Not_Enough", Value=2)]
      eScore_Not_Enough = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eHas_Got_Reward", Value=3)]
      eHas_Got_Reward = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eInner_Error", Value=4)]
      eInner_Error = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eBag_Full", Value=5)]
      eBag_Full = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=4)]
      ModID = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=18)]
      FunID = 18
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stCancelTask")]
  public partial class stCancelTask : global::ProtoBuf.IExtensible
  {
    public stCancelTask() {}
    
    private uint _taskID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"taskID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint taskID
    {
      get { return _taskID; }
      set { _taskID = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=4)]
      ModID = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=19)]
      FunID = 19
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stReqOpenTaskWindow")]
  public partial class stReqOpenTaskWindow : global::ProtoBuf.IExtensible
  {
    public stReqOpenTaskWindow() {}
    
    private uint _charID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charID
    {
      get { return _charID; }
      set { _charID = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=4)]
      ModID = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=20)]
      FunID = 20
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stRefreshAllDailyTask")]
  public partial class stRefreshAllDailyTask : global::ProtoBuf.IExtensible
  {
    public stRefreshAllDailyTask() {}
    
    private readonly global::System.Collections.Generic.List<TaskProto.stSynTaskInfo> _tasks = new global::System.Collections.Generic.List<TaskProto.stSynTaskInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"tasks", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<TaskProto.stSynTaskInfo> tasks
    {
      get { return _tasks; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=4)]
      ModID = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=21)]
      FunID = 21
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"GAME_EVENT_TYPE")]
    public enum GAME_EVENT_TYPE
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ET_FINISH_COPYMAP", Value=1)]
      ET_FINISH_COPYMAP = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ET_RAISE_EQUIP_TO_LV", Value=11)]
      ET_RAISE_EQUIP_TO_LV = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ET_REFINE_EQUIP_TO_LV", Value=12)]
      ET_REFINE_EQUIP_TO_LV = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ET_HERO_BREAK_INTO_LV", Value=13)]
      ET_HERO_BREAK_INTO_LV = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ET_HERO_LEVELUP_TO_LV", Value=14)]
      ET_HERO_LEVELUP_TO_LV = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ET_RAISE_SKILL_TO_LV", Value=15)]
      ET_RAISE_SKILL_TO_LV = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ET_EQUIP_FUWEN_NUM", Value=16)]
      ET_EQUIP_FUWEN_NUM = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ET_RAISE_FUWEN_TO_LV", Value=17)]
      ET_RAISE_FUWEN_TO_LV = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ET_COLLECT_FASHION_NUM", Value=18)]
      ET_COLLECT_FASHION_NUM = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ET_DRAW_NUM", Value=31)]
      ET_DRAW_NUM = 31,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ET_CAPTRURE_TREASURE_NUM", Value=32)]
      ET_CAPTRURE_TREASURE_NUM = 32,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ET_ARENA_NUM", Value=33)]
      ET_ARENA_NUM = 33,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ET_TEAM_FINISH_COPYMAP_NUM", Value=34)]
      ET_TEAM_FINISH_COPYMAP_NUM = 34,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ET_DIANFENG_PK_NUM", Value=35)]
      ET_DIANFENG_PK_NUM = 35,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ET_REALTIME_COPYMAP_NUM", Value=36)]
      ET_REALTIME_COPYMAP_NUM = 36,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ET_LEITAI_COPYMAP_NUM", Value=37)]
      ET_LEITAI_COPYMAP_NUM = 37,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ET_SHENGCUN_COPYMAP_NUM", Value=38)]
      ET_SHENGCUN_COPYMAP_NUM = 38,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ET_GOLDCOIN_COPYMAP_NUM", Value=39)]
      ET_GOLDCOIN_COPYMAP_NUM = 39,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ET_ELITE_COPYMAP_NUM", Value=40)]
      ET_ELITE_COPYMAP_NUM = 40,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ET_RAISE_HERO_NUM", Value=42)]
      ET_RAISE_HERO_NUM = 42,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ET_RAISE_SKILL_NUM", Value=43)]
      ET_RAISE_SKILL_NUM = 43,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ET_RAISE_EQUIP_NUM", Value=44)]
      ET_RAISE_EQUIP_NUM = 44,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ET_RAISE_FUWEN_NUM", Value=45)]
      ET_RAISE_FUWEN_NUM = 45,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ET_GET_WELFARE_CARD", Value=51)]
      ET_GET_WELFARE_CARD = 51,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ET_GET_MONTH_CARD", Value=52)]
      ET_GET_MONTH_CARD = 52,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ET_GET_QUARTER_CARD", Value=53)]
      ET_GET_QUARTER_CARD = 53,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ET_GET_YEAR_CARD", Value=54)]
      ET_GET_YEAR_CARD = 54,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ET_GUARD", Value=62)]
      ET_GUARD = 62,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ET_INTERCEPT", Value=63)]
      ET_INTERCEPT = 63,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ET_BUY_SHOP_ITEM_NUM", Value=64)]
      ET_BUY_SHOP_ITEM_NUM = 64,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ET_EXPEDITION_NUM", Value=65)]
      ET_EXPEDITION_NUM = 65,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ET_RESET_RUSH_NUM", Value=66)]
      ET_RESET_RUSH_NUM = 66,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ET_GIVE_LILIAN_NUM", Value=67)]
      ET_GIVE_LILIAN_NUM = 67,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ET_GUILD_PRAY_NUM", Value=68)]
      ET_GUILD_PRAY_NUM = 68
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"TASK_STATUS")]
    public enum TASK_STATUS
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TS_INVALID", Value=0)]
      TS_INVALID = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TS_INCOMPLETE", Value=1)]
      TS_INCOMPLETE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TS_COMPLETE", Value=2)]
      TS_COMPLETE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TS_FAILED", Value=3)]
      TS_FAILED = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TS_REWARD", Value=4)]
      TS_REWARD = 4
    }
  
}