//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Team.proto
// Note: requires additional types generated from: ModID.proto
namespace TeamProto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stReqCreateTeam")]
  public partial class stReqCreateTeam : global::ProtoBuf.IExtensible
  {
    public stReqCreateTeam() {}
    
    private uint _copyMapID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"copyMapID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint copyMapID
    {
      get { return _copyMapID; }
      set { _copyMapID = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=9)]
      ModID = 9
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=1)]
      FunID = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stCreateTeamResult")]
  public partial class stCreateTeamResult : global::ProtoBuf.IExtensible
  {
    public stCreateTeamResult() {}
    
    private TeamProto.stCreateTeamResult.eResult _result = TeamProto.stCreateTeamResult.eResult.eSUCCESS;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(TeamProto.stCreateTeamResult.eResult.eSUCCESS)]
    public TeamProto.stCreateTeamResult.eResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"eResult")]
    public enum eResult
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"eSUCCESS", Value=1)]
      eSUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eHAS_JOIN_IN_TEAM", Value=2)]
      eHAS_JOIN_IN_TEAM = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eINNER_ERROR", Value=3)]
      eINNER_ERROR = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=9)]
      ModID = 9
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=2)]
      FunID = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stSynMemberInfo")]
  public partial class stSynMemberInfo : global::ProtoBuf.IExtensible
  {
    public stSynMemberInfo() {}
    
    private uint _charID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charID
    {
      get { return _charID; }
      set { _charID = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _job = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"job", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint job
    {
      get { return _job; }
      set { _job = value; }
    }
    private uint _sex = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private bool _leader = default(bool);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"leader", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool leader
    {
      get { return _leader; }
      set { _leader = value; }
    }
    private uint _battlePower = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"battlePower", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint battlePower
    {
      get { return _battlePower; }
      set { _battlePower = value; }
    }
    private uint _pos = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private uint _headID = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"headID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint headID
    {
      get { return _headID; }
      set { _headID = value; }
    }
    private uint _bodyID = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"bodyID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint bodyID
    {
      get { return _bodyID; }
      set { _bodyID = value; }
    }
    private uint _weaponID = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"weaponID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint weaponID
    {
      get { return _weaponID; }
      set { _weaponID = value; }
    }
    private uint _cloackID = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"cloackID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cloackID
    {
      get { return _cloackID; }
      set { _cloackID = value; }
    }
    private uint _wingID = default(uint);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"wingID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint wingID
    {
      get { return _wingID; }
      set { _wingID = value; }
    }
    private uint _shoeID = default(uint);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"shoeID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint shoeID
    {
      get { return _shoeID; }
      set { _shoeID = value; }
    }
    private uint _fashionHair = default(uint);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"fashionHair", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint fashionHair
    {
      get { return _fashionHair; }
      set { _fashionHair = value; }
    }
    private uint _fashionFace = default(uint);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"fashionFace", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint fashionFace
    {
      get { return _fashionFace; }
      set { _fashionFace = value; }
    }
    private uint _fashionBody = default(uint);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"fashionBody", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint fashionBody
    {
      get { return _fashionBody; }
      set { _fashionBody = value; }
    }
    private uint _fashionWeapon = default(uint);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"fashionWeapon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint fashionWeapon
    {
      get { return _fashionWeapon; }
      set { _fashionWeapon = value; }
    }
    private uint _fashionShoe = default(uint);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"fashionShoe", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint fashionShoe
    {
      get { return _fashionShoe; }
      set { _fashionShoe = value; }
    }
    private uint _fashionDecoration = default(uint);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"fashionDecoration", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint fashionDecoration
    {
      get { return _fashionDecoration; }
      set { _fashionDecoration = value; }
    }
    private uint _effectID = default(uint);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"effectID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint effectID
    {
      get { return _effectID; }
      set { _effectID = value; }
    }
    private uint _wingBreakLv = default(uint);
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"wingBreakLv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint wingBreakLv
    {
      get { return _wingBreakLv; }
      set { _wingBreakLv = value; }
    }
    private uint _fashionWingID = default(uint);
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"fashionWingID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint fashionWingID
    {
      get { return _fashionWingID; }
      set { _fashionWingID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stRoomInfo")]
  public partial class stRoomInfo : global::ProtoBuf.IExtensible
  {
    public stRoomInfo() {}
    
    private uint _copyMapID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"copyMapID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint copyMapID
    {
      get { return _copyMapID; }
      set { _copyMapID = value; }
    }
    private readonly global::System.Collections.Generic.List<TeamProto.stSynMemberInfo> _members = new global::System.Collections.Generic.List<TeamProto.stSynMemberInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"members", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<TeamProto.stSynMemberInfo> members
    {
      get { return _members; }
    }
  
    private uint _teamID = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"teamID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint teamID
    {
      get { return _teamID; }
      set { _teamID = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=9)]
      ModID = 9
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=3)]
      FunID = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stReqEnterTeam")]
  public partial class stReqEnterTeam : global::ProtoBuf.IExtensible
  {
    public stReqEnterTeam() {}
    
    private uint _teamID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"teamID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint teamID
    {
      get { return _teamID; }
      set { _teamID = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=9)]
      ModID = 9
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=4)]
      FunID = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stEnterTeamResult")]
  public partial class stEnterTeamResult : global::ProtoBuf.IExtensible
  {
    public stEnterTeamResult() {}
    
    private TeamProto.stEnterTeamResult.eResult _result = TeamProto.stEnterTeamResult.eResult.eTeam_Full;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(TeamProto.stEnterTeamResult.eResult.eTeam_Full)]
    public TeamProto.stEnterTeamResult.eResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"eResult")]
    public enum eResult
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"eTeam_Full", Value=1)]
      eTeam_Full = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eTeam_Not_Exist", Value=2)]
      eTeam_Not_Exist = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eTeam_Leader_Busy", Value=3)]
      eTeam_Leader_Busy = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eHas_In_Team", Value=4)]
      eHas_In_Team = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eTeam_Is_Auto_Match", Value=5)]
      eTeam_Is_Auto_Match = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ePos_Has_Member", Value=6)]
      ePos_Has_Member = 6
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=9)]
      ModID = 9
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=5)]
      FunID = 5
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stAddTeamMember")]
  public partial class stAddTeamMember : global::ProtoBuf.IExtensible
  {
    public stAddTeamMember() {}
    
    private uint _pos = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private TeamProto.stSynMemberInfo _memberInfo = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"memberInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public TeamProto.stSynMemberInfo memberInfo
    {
      get { return _memberInfo; }
      set { _memberInfo = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=9)]
      ModID = 9
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=6)]
      FunID = 6
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stReqLeaveTeam")]
  public partial class stReqLeaveTeam : global::ProtoBuf.IExtensible
  {
    public stReqLeaveTeam() {}
    
    private uint _charID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charID
    {
      get { return _charID; }
      set { _charID = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=9)]
      ModID = 9
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=7)]
      FunID = 7
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stNotifyLeaveTeam")]
  public partial class stNotifyLeaveTeam : global::ProtoBuf.IExtensible
  {
    public stNotifyLeaveTeam() {}
    
    private uint _charID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charID
    {
      get { return _charID; }
      set { _charID = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=9)]
      ModID = 9
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=8)]
      FunID = 8
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stReqFireTeam")]
  public partial class stReqFireTeam : global::ProtoBuf.IExtensible
  {
    public stReqFireTeam() {}
    
    private uint _charID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charID
    {
      get { return _charID; }
      set { _charID = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=9)]
      ModID = 9
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=9)]
      FunID = 9
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stNotifyFireTeam")]
  public partial class stNotifyFireTeam : global::ProtoBuf.IExtensible
  {
    public stNotifyFireTeam() {}
    
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=9)]
      ModID = 9
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=10)]
      FunID = 10
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stInviteJoinInTeam")]
  public partial class stInviteJoinInTeam : global::ProtoBuf.IExtensible
  {
    public stInviteJoinInTeam() {}
    
    private uint _charID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charID
    {
      get { return _charID; }
      set { _charID = value; }
    }
    private uint _pos = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private TeamProto.eTeamType _eType = TeamProto.eTeamType.eCopymap_Team;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"eType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(TeamProto.eTeamType.eCopymap_Team)]
    public TeamProto.eTeamType eType
    {
      get { return _eType; }
      set { _eType = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=9)]
      ModID = 9
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=10)]
      FunID = 10
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stInviteJoinInTeamResult")]
  public partial class stInviteJoinInTeamResult : global::ProtoBuf.IExtensible
  {
    public stInviteJoinInTeamResult() {}
    
    private TeamProto.stInviteJoinInTeamResult.eResult _result = TeamProto.stInviteJoinInTeamResult.eResult.USER_OFFLINE;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(TeamProto.stInviteJoinInTeamResult.eResult.USER_OFFLINE)]
    public TeamProto.stInviteJoinInTeamResult.eResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private TeamProto.eTeamType _eType = TeamProto.eTeamType.eCopymap_Team;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"eType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(TeamProto.eTeamType.eCopymap_Team)]
    public TeamProto.eTeamType eType
    {
      get { return _eType; }
      set { _eType = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"eResult")]
    public enum eResult
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"USER_OFFLINE", Value=1)]
      USER_OFFLINE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_LEADER", Value=2)]
      NOT_LEADER = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DISAGREE", Value=3)]
      DISAGREE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TEAM_NOT_EXSIT", Value=4)]
      TEAM_NOT_EXSIT = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_IN_APPLY_LIST", Value=5)]
      NOT_IN_APPLY_LIST = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OTHER", Value=6)]
      OTHER = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COPYMAP_NUM_USE_OUT", Value=7)]
      COPYMAP_NUM_USE_OUT = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TEAM_IS_AUTO_MATCH", Value=8)]
      TEAM_IS_AUTO_MATCH = 8
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=9)]
      ModID = 9
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=11)]
      FunID = 11
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stAskJoinInTeam")]
  public partial class stAskJoinInTeam : global::ProtoBuf.IExtensible
  {
    public stAskJoinInTeam() {}
    
    private uint _teamID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"teamID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint teamID
    {
      get { return _teamID; }
      set { _teamID = value; }
    }
    private string _inviteName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"inviteName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string inviteName
    {
      get { return _inviteName; }
      set { _inviteName = value; }
    }
    private uint _pos = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private TeamProto.eTeamType _eType = TeamProto.eTeamType.eCopymap_Team;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"eType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(TeamProto.eTeamType.eCopymap_Team)]
    public TeamProto.eTeamType eType
    {
      get { return _eType; }
      set { _eType = value; }
    }
    private uint _copymapID = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"copymapID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint copymapID
    {
      get { return _copymapID; }
      set { _copymapID = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=9)]
      ModID = 9
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=12)]
      FunID = 12
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stReplyJoinInTeam")]
  public partial class stReplyJoinInTeam : global::ProtoBuf.IExtensible
  {
    public stReplyJoinInTeam() {}
    
    private uint _teamID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"teamID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint teamID
    {
      get { return _teamID; }
      set { _teamID = value; }
    }
    private bool _agree = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"agree", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool agree
    {
      get { return _agree; }
      set { _agree = value; }
    }
    private uint _pos = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private TeamProto.eTeamType _eType = TeamProto.eTeamType.eCopymap_Team;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"eType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(TeamProto.eTeamType.eCopymap_Team)]
    public TeamProto.eTeamType eType
    {
      get { return _eType; }
      set { _eType = value; }
    }
    private bool _timesUseOut = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"timesUseOut", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool timesUseOut
    {
      get { return _timesUseOut; }
      set { _timesUseOut = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=9)]
      ModID = 9
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=13)]
      FunID = 13
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stReqEnterLv")]
  public partial class stReqEnterLv : global::ProtoBuf.IExtensible
  {
    public stReqEnterLv() {}
    
    private uint _copyMapID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"copyMapID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint copyMapID
    {
      get { return _copyMapID; }
      set { _copyMapID = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=9)]
      ModID = 9
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=14)]
      FunID = 14
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stReqBroadcastInviteCmd")]
  public partial class stReqBroadcastInviteCmd : global::ProtoBuf.IExtensible
  {
    public stReqBroadcastInviteCmd() {}
    
    private uint _charID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charID
    {
      get { return _charID; }
      set { _charID = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=9)]
      ModID = 9
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=15)]
      FunID = 15
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stBroadcastInviteJoinIn")]
  public partial class stBroadcastInviteJoinIn : global::ProtoBuf.IExtensible
  {
    public stBroadcastInviteJoinIn() {}
    
    private uint _teamID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"teamID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint teamID
    {
      get { return _teamID; }
      set { _teamID = value; }
    }
    private uint _charID = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"charID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charID
    {
      get { return _charID; }
      set { _charID = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _job = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"job", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint job
    {
      get { return _job; }
      set { _job = value; }
    }
    private uint _sex = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private uint _battlePower = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"battlePower", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint battlePower
    {
      get { return _battlePower; }
      set { _battlePower = value; }
    }
    private uint _vipLv = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"vipLv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint vipLv
    {
      get { return _vipLv; }
      set { _vipLv = value; }
    }
    private uint _copyMapID = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"copyMapID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint copyMapID
    {
      get { return _copyMapID; }
      set { _copyMapID = value; }
    }
    private uint _photoID = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"photoID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint photoID
    {
      get { return _photoID; }
      set { _photoID = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=9)]
      ModID = 9
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=16)]
      FunID = 16
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stReqAutoMatchTeam")]
  public partial class stReqAutoMatchTeam : global::ProtoBuf.IExtensible
  {
    public stReqAutoMatchTeam() {}
    
    private uint _charID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charID
    {
      get { return _charID; }
      set { _charID = value; }
    }
    private uint _copyMapID = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"copyMapID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint copyMapID
    {
      get { return _copyMapID; }
      set { _copyMapID = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=9)]
      ModID = 9
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=17)]
      FunID = 17
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stWaitMatchTeam")]
  public partial class stWaitMatchTeam : global::ProtoBuf.IExtensible
  {
    public stWaitMatchTeam() {}
    
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=9)]
      ModID = 9
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=18)]
      FunID = 18
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stMathcTeamSuccess")]
  public partial class stMathcTeamSuccess : global::ProtoBuf.IExtensible
  {
    public stMathcTeamSuccess() {}
    
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=9)]
      ModID = 9
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=19)]
      FunID = 19
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stCancelAutoMatchTeam")]
  public partial class stCancelAutoMatchTeam : global::ProtoBuf.IExtensible
  {
    public stCancelAutoMatchTeam() {}
    
    private uint _charID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charID
    {
      get { return _charID; }
      set { _charID = value; }
    }
    private uint _copyMapID = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"copyMapID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint copyMapID
    {
      get { return _copyMapID; }
      set { _copyMapID = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=9)]
      ModID = 9
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=20)]
      FunID = 20
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stCancelAutoMatchTeamResult")]
  public partial class stCancelAutoMatchTeamResult : global::ProtoBuf.IExtensible
  {
    public stCancelAutoMatchTeamResult() {}
    
    private TeamProto.stCancelAutoMatchTeamResult.eResult _result = TeamProto.stCancelAutoMatchTeamResult.eResult.eSUCCESS;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(TeamProto.stCancelAutoMatchTeamResult.eResult.eSUCCESS)]
    public TeamProto.stCancelAutoMatchTeamResult.eResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"eResult")]
    public enum eResult
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"eSUCCESS", Value=1)]
      eSUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eFAIL", Value=2)]
      eFAIL = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=9)]
      ModID = 9
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=21)]
      FunID = 21
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stReqFirstKillInfoByID")]
  public partial class stReqFirstKillInfoByID : global::ProtoBuf.IExtensible
  {
    public stReqFirstKillInfoByID() {}
    
    private uint _levelID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"levelID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint levelID
    {
      get { return _levelID; }
      set { _levelID = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=9)]
      ModID = 9
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=22)]
      FunID = 22
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stRetFirstKillInfo")]
  public partial class stRetFirstKillInfo : global::ProtoBuf.IExtensible
  {
    public stRetFirstKillInfo() {}
    
    private uint _copymapID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"copymapID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint copymapID
    {
      get { return _copymapID; }
      set { _copymapID = value; }
    }
    private uint _charID1 = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"charID1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charID1
    {
      get { return _charID1; }
      set { _charID1 = value; }
    }
    private uint _job1 = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"job1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint job1
    {
      get { return _job1; }
      set { _job1 = value; }
    }
    private uint _sex1 = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"sex1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sex1
    {
      get { return _sex1; }
      set { _sex1 = value; }
    }
    private string _name1 = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"name1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name1
    {
      get { return _name1; }
      set { _name1 = value; }
    }
    private uint _level1 = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"level1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level1
    {
      get { return _level1; }
      set { _level1 = value; }
    }
    private uint _battlePower1 = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"battlePower1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint battlePower1
    {
      get { return _battlePower1; }
      set { _battlePower1 = value; }
    }
    private uint _charID2 = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"charID2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charID2
    {
      get { return _charID2; }
      set { _charID2 = value; }
    }
    private uint _job2 = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"job2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint job2
    {
      get { return _job2; }
      set { _job2 = value; }
    }
    private uint _sex2 = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"sex2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sex2
    {
      get { return _sex2; }
      set { _sex2 = value; }
    }
    private string _name2 = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"name2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name2
    {
      get { return _name2; }
      set { _name2 = value; }
    }
    private uint _level2 = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"level2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level2
    {
      get { return _level2; }
      set { _level2 = value; }
    }
    private uint _battlePower2 = default(uint);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"battlePower2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint battlePower2
    {
      get { return _battlePower2; }
      set { _battlePower2 = value; }
    }
    private uint _charID3 = default(uint);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"charID3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charID3
    {
      get { return _charID3; }
      set { _charID3 = value; }
    }
    private uint _job3 = default(uint);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"job3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint job3
    {
      get { return _job3; }
      set { _job3 = value; }
    }
    private uint _sex3 = default(uint);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"sex3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sex3
    {
      get { return _sex3; }
      set { _sex3 = value; }
    }
    private string _name3 = "";
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"name3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name3
    {
      get { return _name3; }
      set { _name3 = value; }
    }
    private uint _level3 = default(uint);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"level3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level3
    {
      get { return _level3; }
      set { _level3 = value; }
    }
    private uint _battlePower3 = default(uint);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"battlePower3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint battlePower3
    {
      get { return _battlePower3; }
      set { _battlePower3 = value; }
    }
    private uint _killTime = default(uint);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"killTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint killTime
    {
      get { return _killTime; }
      set { _killTime = value; }
    }
    private uint _photoID1 = default(uint);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"photoID1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint photoID1
    {
      get { return _photoID1; }
      set { _photoID1 = value; }
    }
    private uint _photoID2 = default(uint);
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"photoID2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint photoID2
    {
      get { return _photoID2; }
      set { _photoID2 = value; }
    }
    private uint _photoID3 = default(uint);
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"photoID3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint photoID3
    {
      get { return _photoID3; }
      set { _photoID3 = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=9)]
      ModID = 9
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=23)]
      FunID = 23
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stReqRealTimeSingleMatch")]
  public partial class stReqRealTimeSingleMatch : global::ProtoBuf.IExtensible
  {
    public stReqRealTimeSingleMatch() {}
    
    private TeamProto.eRealTimePKType _eType = TeamProto.eRealTimePKType.eRealTimePKType_KillAll;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"eType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(TeamProto.eRealTimePKType.eRealTimePKType_KillAll)]
    public TeamProto.eRealTimePKType eType
    {
      get { return _eType; }
      set { _eType = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=9)]
      ModID = 9
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=24)]
      FunID = 24
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stRealTimeSingleMatchWait")]
  public partial class stRealTimeSingleMatchWait : global::ProtoBuf.IExtensible
  {
    public stRealTimeSingleMatchWait() {}
    
    private TeamProto.eRealTimePKType _eType = TeamProto.eRealTimePKType.eRealTimePKType_KillAll;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"eType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(TeamProto.eRealTimePKType.eRealTimePKType_KillAll)]
    public TeamProto.eRealTimePKType eType
    {
      get { return _eType; }
      set { _eType = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=9)]
      ModID = 9
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=25)]
      FunID = 25
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stReqCancelRealTimeSingleMatch")]
  public partial class stReqCancelRealTimeSingleMatch : global::ProtoBuf.IExtensible
  {
    public stReqCancelRealTimeSingleMatch() {}
    
    private TeamProto.eRealTimePKType _eType = TeamProto.eRealTimePKType.eRealTimePKType_KillAll;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"eType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(TeamProto.eRealTimePKType.eRealTimePKType_KillAll)]
    public TeamProto.eRealTimePKType eType
    {
      get { return _eType; }
      set { _eType = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=9)]
      ModID = 9
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=26)]
      FunID = 26
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stCancelRealTimeSingleMatchResult")]
  public partial class stCancelRealTimeSingleMatchResult : global::ProtoBuf.IExtensible
  {
    public stCancelRealTimeSingleMatchResult() {}
    
    private bool _success = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"success", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool success
    {
      get { return _success; }
      set { _success = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=9)]
      ModID = 9
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=27)]
      FunID = 27
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stReqRealTimeTeamMatch")]
  public partial class stReqRealTimeTeamMatch : global::ProtoBuf.IExtensible
  {
    public stReqRealTimeTeamMatch() {}
    
    private TeamProto.eRealTimePKType _eType = TeamProto.eRealTimePKType.eRealTimePKType_KillAll;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"eType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(TeamProto.eRealTimePKType.eRealTimePKType_KillAll)]
    public TeamProto.eRealTimePKType eType
    {
      get { return _eType; }
      set { _eType = value; }
    }
    private uint _teamID = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"teamID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint teamID
    {
      get { return _teamID; }
      set { _teamID = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=9)]
      ModID = 9
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=28)]
      FunID = 28
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stRealTimeTeamMatchWait")]
  public partial class stRealTimeTeamMatchWait : global::ProtoBuf.IExtensible
  {
    public stRealTimeTeamMatchWait() {}
    
    private TeamProto.eRealTimePKType _eType = TeamProto.eRealTimePKType.eRealTimePKType_KillAll;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"eType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(TeamProto.eRealTimePKType.eRealTimePKType_KillAll)]
    public TeamProto.eRealTimePKType eType
    {
      get { return _eType; }
      set { _eType = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=9)]
      ModID = 9
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=29)]
      FunID = 29
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stReqCancelRealTimeTeamMatch")]
  public partial class stReqCancelRealTimeTeamMatch : global::ProtoBuf.IExtensible
  {
    public stReqCancelRealTimeTeamMatch() {}
    
    private TeamProto.eRealTimePKType _eType = TeamProto.eRealTimePKType.eRealTimePKType_KillAll;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"eType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(TeamProto.eRealTimePKType.eRealTimePKType_KillAll)]
    public TeamProto.eRealTimePKType eType
    {
      get { return _eType; }
      set { _eType = value; }
    }
    private uint _teamID = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"teamID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint teamID
    {
      get { return _teamID; }
      set { _teamID = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=9)]
      ModID = 9
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=30)]
      FunID = 30
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stCancelRealTimeTeamMatchResult")]
  public partial class stCancelRealTimeTeamMatchResult : global::ProtoBuf.IExtensible
  {
    public stCancelRealTimeTeamMatchResult() {}
    
    private bool _success = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"success", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool success
    {
      get { return _success; }
      set { _success = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=9)]
      ModID = 9
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=31)]
      FunID = 31
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stRealTimePKNotOpen")]
  public partial class stRealTimePKNotOpen : global::ProtoBuf.IExtensible
  {
    public stRealTimePKNotOpen() {}
    
    private TeamProto.eRealTimePKType _eType = TeamProto.eRealTimePKType.eRealTimePKType_KillAll;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"eType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(TeamProto.eRealTimePKType.eRealTimePKType_KillAll)]
    public TeamProto.eRealTimePKType eType
    {
      get { return _eType; }
      set { _eType = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProtoModID")]
    public enum ProtoModID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModID", Value=9)]
      ModID = 9
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoFunID")]
    public enum ProtoFunID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FunID", Value=32)]
      FunID = 32
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"eTeamType")]
    public enum eTeamType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"eCopymap_Team", Value=1)]
      eCopymap_Team = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eRealTime_Team", Value=2)]
      eRealTime_Team = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eGuild_Copymap_Team", Value=3)]
      eGuild_Copymap_Team = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eSpouse_Inviti", Value=4)]
      eSpouse_Inviti = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eRealTimePKType")]
    public enum eRealTimePKType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"eRealTimePKType_KillAll", Value=1)]
      eRealTimePKType_KillAll = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eRealTimePKType_Finish", Value=2)]
      eRealTimePKType_Finish = 2
    }
  
}