// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ModID.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "ModID.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Proto {

namespace {

const ::google::protobuf::EnumDescriptor* ModID_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_ModID_2eproto() {
  protobuf_AddDesc_ModID_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "ModID.proto");
  GOOGLE_CHECK(file != NULL);
  ModID_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_ModID_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_ModID_2eproto() {
}

void protobuf_AddDesc_ModID_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\013ModID.proto\022\005Proto*\233\001\n\005ModID\022\r\n\tLOGIN_"
    "MOD\020\001\022\014\n\010ROLE_MOD\020\002\022\013\n\007MAP_MOD\020\003\022\014\n\010TASK"
    "_MOD\020\004\022\016\n\nFRIEND_MOD\020\005\022\020\n\014SORTLIST_MOD\020\006"
    "\022\r\n\tGUILD_MOD\020\007\022\014\n\010MISC_MOD\020\010\022\014\n\010TEAM_MO"
    "D\020\t\022\r\n\tMISC2_MOD\020\n", 178);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ModID.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_ModID_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_ModID_2eproto {
  StaticDescriptorInitializer_ModID_2eproto() {
    protobuf_AddDesc_ModID_2eproto();
  }
} static_descriptor_initializer_ModID_2eproto_;
const ::google::protobuf::EnumDescriptor* ModID_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ModID_descriptor_;
}
bool ModID_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Proto

// @@protoc_insertion_point(global_scope)
